name: "\U0001F680 Request a change"
description: "Request a new feature or change to an existing feature"
title: "Change Request: (fill in)"
labels:
    - enhancement
body:
    - type: textarea
      attributes:
          label: What problem do you want to solve?
          description: |
              Please explain your use case in as much detail as possible without referring to a specific solution.
          placeholder: |
              ModuleImporter currently...
      validations:
          required: true
    - type: textarea
      attributes:
          label: What do you think is the correct solution?
          description: |
              Please explain how you'd like to change ModuleImporter to address the problem.
          placeholder: |
              I'd like ModuleImporter to...
      validations:
          required: true
    - type: checkboxes
      attributes:
          label: Participation
          options:
              - label: I am willing to submit a pull request for this change.
                required: false
    - type: textarea
      attributes:
          label: Additional comments
          description: Is there anything else you'd like to mention?
