blank_issues_enabled: false
contact_links:
    - name: 🔒 Report a Security Vulnerability
      url: https://github.com/humanwhocodes/module-importer/security/advisories/new
      about: Privately report a security vulnerability to the team
